### ISSUE TITLE
Connection error after some time

### ISSUE THREAD

**Issue by t-liu93** [Koenkk/Z-Stack-firmware#209] opened 2020-09-23 09:54 UTC
I have facing an issue that my zigbee network starts failing after some time. 

* Time to happen:
After days of normal running 
OR after I have triggered firmware updated (i.e. after large amount of data transmitting)

When the network starts failing, I am not able to control my light in a good manner, the log shows a lots of error message including ```MEM_ERROR``` or ```

I could only do a power cycle of the stick (unplug and plug again) then restart zigbee2mqtt plugin in home assistant to make it working again.

I am running Z-Stack_Home_1.2 (source_routing)

I have attached some log about it:
```
info  2020-09-22 10:18:15: MQTT publish: topic 'zigbee2mqtt/light_north_bedroom_6', payload '{"brightness":0,"state":"OFF","update_available":false}'
$:4,"data":{"type":"Buffer","data":[25,28,2,149]}}' failed with status '(0x10: MEM_ERROR)' (expected '(0x00: SUCCESS)'))    at Znp.<anonymous> (/zigbee2mqtt-1.14.4/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/zigbee2mqtt-1.14.4/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58))
```

**Comment by Koenkk** [comment] 2020-09-25 12:52
Probably duplicate of https://github.com/Koenkk/zigbee2mqtt/issues/4307, if on the latest dev branch Zigbee2MQTT still fails please provide the herdsman debug logging from start till crash in #4307. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Closed by Koenkk** 2020-09-25 12:52 UTC
