### ISSUE TITLE
Unknown record type: 3

### ISSUE THREAD

**Issue by tsugawa** [Koenkk/Z-Stack-firmware#460] opened 2023-06-25 06:57 UTC
SmartRF fails with this message. 

I have SONOFF Zigbee 3.0 USB Dongle Plus ZBDongle-P with CC1352P2_CC2652P_launchpad_coordinator_20221226 version.

>Initiate access to target: COM15 using 2-pin cJTAG.
>Reading file: C:/Users/Ricardo/Desktop/Zigbee/CC1352P2_CC2652P_launchpad_coordinator_20230507.hex.
>Unknown record type: 3.
>Reset target ...
>Reset of target successful.

**Comment by Koenkk** [comment] 2023-06-25 07:00
Duplicate of https://github.com/Koenkk/Z-Stack-firmware/issues/455

**Closed by Koenkk** 2023-06-25 07:00 UTC
