### ISSUE TITLE
Flashing

### ISSUE THREAD

**Issue by Aguasclaras5** [Koenkk/Z-Stack-firmware#432] opened 2023-03-02 18:04 UTC
Coordinator firmware flashes no problem ( using smartRF flash programmer.) When flashing CoOrdinator get status message
>Initiate access to target: COM3 using 2-pin cJTAG.
>Reading file: D:/Router.hex.
>Unknown record type: 3.
>Reset target ...
>Reset of target successful.

**Comment by Koenkk** [comment] 2023-03-02 18:50
Duplicate of https://github.com/Koenkk/Z-Stack-firmware/issues/397

**Closed by Koenkk** 2023-03-02 18:50 UTC
