### ISSUE TITLE
Unknown record type: 3 with 20230507

### ISSUE THREAD

**Issue by smarteshome2020** [Koenkk/Z-Stack-firmware#481] opened 2023-10-29 18:28 UTC
Hi,

i try to flash my Sonoff Stick from 20220219 to 20230507 and it fails.
Flash from 20220219 -> 20221226 works
Flash from 20221226 -> 20230507 fails (log below)

Du you have a hint for me? 

****20221226 -> 20230507 fails** same error like 20220219 -> 20230507** 
>Reset of target successful.
>Initiate access to target: COM6 using 2-pin cJTAG.
>Reading file: E:/Download/CC1352P2_CC2652P_launchpad_coordinator_20230507/CC1352P2_CC2652P_launchpad_coordinator_20230507.hex.
>Unknown record type: 3.
>Reset target ...

**20220219 -> 20221226 works**
>Reset of target successful.
>Initiate access to target: COM6 using 2-pin cJTAG.
>Reading file: E:/Download/CC1352P2_CC2652P_launchpad_coordinator_20221226/CC1352P2_CC2652P_launchpad_coordinator_20221226.hex.
>Start flash erase ...

**Comment by Koenkk** [comment] 2023-10-29 18:43
Duplicate of https://github.com/Koenkk/Z-Stack-firmware/issues/455

**Closed by Koenkk** 2023-10-29 18:43 UTC

**Comment by smarteshome2020** [comment] 2023-10-29 18:45
thanks and sorry fr the duplicate :-)
