### ISSUE TITLE
Unknown record type: 3

### ISSUE THREAD

**Issue by grannysmith59** [Koenkk/Z-Stack-firmware#428] opened 2023-02-24 17:28 UTC
Tried to flash latest router firmware (CC1352P2_CC2652P_launchpad_router_20221102) to Sonoff Zigbee 3.0 dongle plus using Flash Programmer 2, but received error: Unknown record type: 3.

I was able to flash "CC1352P2_CC2652P_launchpad_router_20220125"

**Comment by rwunsch** [comment] 2023-02-24 17:30
Could you please check: 
https://github.com/Koenkk/Z-Stack-firmware/issues/423 ?

**Comment by rwunsch** [comment] 2023-02-24 17:31
and/or:
https://github.com/Koenkk/Z-Stack-firmware/issues/397

**Comment by Koenkk** [comment] 2023-02-25 09:27
Duplicate of https://github.com/Koenkk/Z-Stack-firmware/issues/397

**Closed by Koenkk** 2023-02-25 09:27 UTC
